import { useEffect, useState } from 'react'
import type { Media } from './types'
import { createImageThumbnail, mediaPreviewUrl, revokeMediaUrl, saveMediaFile } from './mediaStorage'
import { attachMedia, detachMedia, reorderMedia } from './mediaDomain'
import { db } from './db'

export function AttachmentPanel({mediaIds,onChange}:{mediaIds:string[];onChange:(ids:string[])=>void}){const [media,setMedia]=useState<Media[]>([]),[status,setStatus]=useState('');useEffect(()=>{db.media.bulkGet(mediaIds).then(items=>setMedia(items.filter(Boolean) as Media[]))},[mediaIds]);async function importFiles(files:FileList|null){if(!files?.length||status==='Importing…')return;setStatus('Importing…');const ids=[...mediaIds];for(const file of Array.from(files)){try{let item=await saveMediaFile(file);if(item.mediaType==='image')item=await createImageThumbnail(item);ids.push(item.id)}catch{setStatus(`Could not import ${file.name}`)}}onChange([...new Set(ids)]);setStatus('Ready')}return <section className="attachments" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();importFiles(e.dataTransfer.files)}}><div className="editor-head"><span className="eyebrow">ATTACHMENTS {status&&`· ${status}`}</span><label className="quiet">Select files<input hidden type="file" multiple accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.txt" onChange={e=>importFiles(e.target.files)}/></label></div>{!media.length&&<p className="empty">No media attached yet.</p>}<div className="attachment-list">{media.map((item,index)=><Attachment key={item.id} media={item} onDetach={()=>onChange(detachMedia({mediaIds} as never,item.id).mediaIds)} onMove={to=>onChange(reorderMedia({mediaIds} as never,index,to).mediaIds)} index={index} total={media.length}/>)}</div></section>}
function Attachment({media,onDetach,onMove,index,total}:{media:Media;onDetach:()=>void;onMove:(to:number)=>void;index:number;total:number}){const [url,setUrl]=useState<string>();useEffect(()=>{mediaPreviewUrl(media).then(setUrl);return()=>revokeMediaUrl(url)},[media.id]);return <article className="attachment"><Preview media={media} url={url}/><div><strong>{media.title||media.filename}</strong><small>{media.mediaType} · {(media.byteSize/1024).toFixed(0)} KB</small><input placeholder="Title" defaultValue={media.title} onBlur={async e=>db.media.put({...media,title:e.target.value})}/><input placeholder="Caption" defaultValue={media.caption} onBlur={async e=>db.media.put({...media,caption:e.target.value})}/></div><div><button type="button" disabled={!index} onClick={()=>onMove(index-1)}>↑</button><button type="button" disabled={index===total-1} onClick={()=>onMove(index+1)}>↓</button><button type="button" className="danger" onClick={onDetach}>Remove</button></div></article>}
function Preview({media,url}:{media:Media;url?:string}){if(media.mediaType==='image')return url?<img src={url} alt={media.caption||media.filename}/>:<span>Image</span>;if(media.mediaType==='audio')return url?<audio controls src={url}/>:<span>Audio</span>;if(media.mediaType==='video')return url?<video controls src={url}/>:<span>Video</span>;return <span>Document</span>}
