import Dexie, { type EntityTable } from 'dexie'
import type { Entry, Person, Place, Tag, LifeEra, Archive, Media, MediaFile } from './types'
import { detachReference } from './domain'
export const db = new Dexie('life-line-diary') as Dexie & { entries:EntityTable<Entry,'id'>; people:EntityTable<Person,'id'>; places:EntityTable<Place,'id'>; tags:EntityTable<Tag,'id'>; eras:EntityTable<LifeEra,'id'>; media:EntityTable<Media,'id'>; mediaFiles:EntityTable<MediaFile,'key'> }
db.version(1).stores({ entries:'id, entryType, updatedAt, *tagIds, *peopleIds', people:'id,name', places:'id,name', tags:'id,name', eras:'id,name' })
db.version(2).stores({ entries:'id, entryType, updatedAt, *tagIds, *peopleIds, *mediaIds', people:'id,name', places:'id,name', tags:'id,name', eras:'id,name', media:'id,mediaType,filename,importedAt', mediaFiles:'key' })
export async function archive():Promise<Archive>{ const [entries,people,places,tags,eras,media]=await Promise.all([db.entries.toArray(),db.people.toArray(),db.places.toArray(),db.tags.toArray(),db.eras.toArray(),db.media.toArray()]); return {entries,people,places,tags,eras,media} }
export async function importArchive(data:Archive, mode:'merge'|'replace') { if(mode==='replace') await db.transaction('rw',[db.entries,db.people,db.places,db.tags,db.eras,db.media],()=>Promise.all([db.entries.clear(),db.people.clear(),db.places.clear(),db.tags.clear(),db.eras.clear(),db.media.clear()])); await db.transaction('rw',[db.entries,db.people,db.places,db.tags,db.eras,db.media],()=>Promise.all([db.entries.bulkPut(data.entries),db.people.bulkPut(data.people),db.places.bulkPut(data.places),db.tags.bulkPut(data.tags),db.eras.bulkPut(data.eras),data.media?db.media.bulkPut(data.media):Promise.resolve()])) }
export async function removeEntity(kind:'people'|'places'|'tags'|'eras', id:string){ await db.transaction('rw',[db.entries,db.people,db.places,db.tags,db.eras],async()=>{ if(kind!=='eras'){const field=kind==='people'?'peopleIds':kind==='places'?'placeIds':'tagIds';const changed=detachReference(await db.entries.toArray(),field,id).filter((entry,index,all)=>entry!==all[index]); const original=await db.entries.toArray(); const updates=changed.filter(entry=>original.find(x=>x.id===entry.id)?.[field].length!==entry[field].length); if(updates.length) await db.entries.bulkPut(updates)} await db.table(kind).delete(id) }) }
