import { useMemo, useState } from 'react'
import { chronologicalEras, hasDuplicateTag, referencesFor } from './domain'
import type { Archive, LifeEra, Person, Place, Tag } from './types'
type Kind='people'|'places'|'tags'|'eras'
type Entity=Person|Place|Tag|LifeEra
const uid=()=>crypto.randomUUID()
export function EntityManager({kind,data,onSave,onDelete,onOpenEntries}:{kind:string;data:Archive;onSave:(kind:Kind,item:Entity)=>Promise<void>;onDelete:(kind:Kind,item:Entity)=>void;onOpenEntries:(field:'peopleIds'|'placeIds'|'tagIds',id:string)=>void}){
 const entityKind=kind as Kind; const [search,setSearch]=useState(''); const [editing,setEditing]=useState<Entity|null>(null);const config={people:{title:'People',field:'peopleIds',items:data.people},places:{title:'Places',field:'placeIds',items:data.places},tags:{title:'Tags',field:'tagIds',items:data.tags},eras:{title:'Life eras',field:null,items:chronologicalEras(data.eras)}}[entityKind] as {title:string;field:'peopleIds'|'placeIds'|'tagIds'|null;items:Entity[]}
 const items=useMemo(()=>config.items.filter(item=>`${item.name} ${'description'in item?item.description??'':''}`.toLowerCase().includes(search.toLowerCase())),[config.items,search])
 const create=()=>setEditing(entityKind==='people'?{id:uid(),name:'',relationship:'',notes:''}:entityKind==='places'?{id:uid(),name:'',description:''}:entityKind==='tags'?{id:uid(),name:'',color:'#5d7fa3'}:{id:uid(),name:'',description:''})
 return <section className="manager"><div className="manager-head"><div><span className="eyebrow">LIFE DATA</span><h2>{config.title}</h2></div><button className="primary" onClick={create}>+ Add {entityKind==='eras'?'era':entityKind.slice(0,-1)}</button></div><input className="manager-search" placeholder={`Search ${config.title.toLowerCase()}…`} value={search} onChange={e=>setSearch(e.target.value)}/><div className="entity-list">{items.map(item=>{const count=config.field?referencesFor(data.entries,config.field,item.id).length:0;return <article key={item.id}><div><h3>{item.name}</h3>{'nickname'in item&&item.nickname&&<p>{item.nickname}</p>}{'description'in item&&item.description&&<p>{item.description}</p>}{'start'in item&&<p>{item.start?.slice(0,4)??'Undated'} {item.end&&`– ${item.end.slice(0,4)}`}</p>}</div><div className="entity-actions">{config.field&&<button className="quiet" onClick={()=>onOpenEntries(config.field!,item.id)}>{count} {count===1?'memory':'memories'}</button>}<button className="quiet" onClick={()=>setEditing(item)}>Edit</button><button className="danger" onClick={()=>onDelete(entityKind,item)}>Delete</button></div></article>})}{!items.length&&<p className="empty">No matches yet.</p>}</div>{editing&&<EntityDialog kind={entityKind} value={editing} tags={data.tags} onClose={()=>setEditing(null)} onSave={async item=>{if(entityKind==='tags'&&hasDuplicateTag(data.tags,item.name,item.id)){alert('A tag with that name already exists.');return}await onSave(entityKind,item);setEditing(null)}}/>}</section>
}
function EntityDialog({kind,value,tags,onClose,onSave}:{kind:Kind;value:Entity;tags:Tag[];onClose:()=>void;onSave:(value:Entity)=>void;}){const [item,setItem]=useState(value);const set=(key:string,value:string)=>setItem(current=>({...current,[key]:value}));return <div className="overlay"><form className="editor compact" onSubmit={e=>{e.preventDefault();if(item.name.trim())onSave({...item,name:item.name.trim()})}}><div className="editor-head"><span className="eyebrow">{value.name?'EDIT':'NEW'} {kind.slice(0,-1).toUpperCase()}</span><button type="button" className="close" onClick={onClose}>×</button></div><label>Name<input autoFocus value={item.name} onChange={e=>set('name',e.target.value)} required/></label>{kind==='people'&&<><label>Nickname<input value={(item as Person).nickname??''} onChange={e=>set('nickname',e.target.value)}/></label><label>Relationship<input value={(item as Person).relationship??''} onChange={e=>set('relationship',e.target.value)}/></label></>}{kind==='places'&&<><label>Description<textarea value={(item as Place).description??''} onChange={e=>set('description',e.target.value)}/></label><label>Latitude (optional)<input type="number" value={(item as Place).latitude??''} onChange={e=>set('latitude',e.target.value)}/></label></>}{kind==='tags'&&<label>Color<input type="color" value={(item as Tag).color} onChange={e=>set('color',e.target.value)}/></label>}{kind==='eras'&&<><label>Start<input type="date" value={(item as LifeEra).start??''} onChange={e=>set('start',e.target.value)}/></label><label>End<input type="date" value={(item as LifeEra).end??''} onChange={e=>set('end',e.target.value)}/></label><label>Description<textarea value={(item as LifeEra).description??''} onChange={e=>set('description',e.target.value)}/></label></>}<div className="editor-actions"><span/><button type="button" className="quiet" onClick={onClose}>Cancel</button><button className="primary">Save</button></div></form></div>}
