import { db } from './db'
import type { Media, MediaType } from './types'

const typeFor=(file:File):MediaType=>file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':'document'
const keyFor=(id:string)=>`media/${id}`
export async function storageInfo(){const estimate=await navigator.storage?.estimate?.();const persistent=await navigator.storage?.persisted?.();return {usage:estimate?.usage??0,quota:estimate?.quota??0,persistent:!!persistent}}
export async function saveMediaFile(file:File):Promise<Media>{const {usage,quota}=await storageInfo();if(quota&&file.size>quota-usage)throw new Error('There is not enough browser storage for this file.');const id=crypto.randomUUID(),storageKey=keyFor(id);const media:Media={id,mediaType:typeFor(file),filename:file.name,mimeType:file.type||'application/octet-stream',byteSize:file.size,importedAt:new Date().toISOString(),storageKey,version:1};await db.transaction('rw',[db.media,db.mediaFiles],async()=>{await db.mediaFiles.put({key:storageKey,blob:file});await db.media.put(media)});return media}
export async function readMediaFile(media:Media){return (await db.mediaFiles.get(media.storageKey))?.blob}
export async function createMediaUrl(media:Media){const blob=await readMediaFile(media);return blob?URL.createObjectURL(blob):undefined}
export const revokeMediaUrl=(url?:string)=>{if(url)URL.revokeObjectURL(url)}
export async function createImageThumbnail(media:Media){if(media.mediaType!=='image')return media; if(media.thumbnailKey)return media;const original=await readMediaFile(media);if(!original)return media;const url=URL.createObjectURL(original);try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const element=new Image();element.onload=()=>resolve(element);element.onerror=reject;element.src=url});const scale=Math.min(1,480/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));if(!blob)return media;const thumbnailKey=`${media.storageKey}/thumbnail`;await db.mediaFiles.put({key:thumbnailKey,blob});const updated={...media,width:image.width,height:image.height,thumbnailKey};await db.media.put(updated);return updated}finally{URL.revokeObjectURL(url)}}
export async function mediaPreviewUrl(media:Media){const preview=media.thumbnailKey?await db.mediaFiles.get(media.thumbnailKey):undefined;return preview?URL.createObjectURL(preview.blob):createMediaUrl(media)}
export async function deleteMediaFile(media:Media){const linked=await db.entries.filter(entry=>entry.mediaIds.includes(media.id)).count();if(linked)throw new Error('Media is still attached to a memory. Detach it first.');await db.transaction('rw',[db.media,db.mediaFiles],()=>Promise.all([db.media.delete(media.id),db.mediaFiles.delete(media.storageKey),media.thumbnailKey?db.mediaFiles.delete(media.thumbnailKey):Promise.resolve()]))}
