import type { Archive } from './types'
const id=(name:string)=>name.toLowerCase().replaceAll(' ','-')
export const seed:Archive={
 people:[{id:'p-dad',name:'Dad',relationship:'Family'},{id:'p-grandma',name:'Grandma Rosa',relationship:'Family'}],
 places:[{id:'pl-phoenix',name:'Phoenix, Arizona'},{id:'pl-grandma',name:"Grandma's house",description:'The living-room floor was always the best place to play.'}],
 tags:[{id:'t-childhood',name:'childhood',color:'#d97757'},{id:'t-family',name:'family',color:'#5d7fa3'},{id:'t-school',name:'school',color:'#728b62'},{id:'t-funny',name:'funny',color:'#a7779d'}],
 eras:[{id:'e-childhood',name:'Childhood',start:'1998-01-01',end:'2009-12-31',description:'The early years.'},{id:'e-phoenix',name:'Phoenix Years',start:'2010-01-01',description:'Growing roots in the desert.'}],
 entries: [
  {id:'m-first-day',title:'First day at a new school',body:'I remember the yellow backpack and trying to find the right room before the bell.',entryType:'milestone',eventDate:{precision:'exact',start:'2004-08-16',confidence:'confirmed'},recordTime:'2026-09-20T10:00:00Z',createdAt:'2026-09-20T10:00:00Z',updatedAt:'2026-09-20T10:00:00Z',importance:4,status:'active',peopleIds:['p-dad'],placeIds:['pl-phoenix'],tagIds:['t-school'],mediaIds:[],relatedEntryIds:[]},
  {id:'m-summer',title:'The summer we learned card tricks',body:'Long evenings at the kitchen table, practicing the same shuffle until it almost worked.',entryType:'memory',eventDate:{precision:'season',start:'2008-06-01',season:'Summer',confidence:'likely'},recordTime:'2026-09-20T10:00:00Z',createdAt:'2026-09-20T10:00:00Z',updatedAt:'2026-09-20T10:00:00Z',importance:2,status:'active',peopleIds:['p-dad'],placeIds:[],tagIds:['t-family'],mediaIds:[],relatedEntryIds:[]},
  {id:'m-move',title:'Moving to Phoenix',body:'Everything felt big and bright. We drove past palm trees and decided this would be home.',entryType:'event',eventDate:{precision:'year',start:'2010-01-01',confidence:'confirmed'},recordTime:'2026-09-20T10:00:00Z',createdAt:'2026-09-20T10:00:00Z',updatedAt:'2026-09-20T10:00:00Z',importance:5,status:'active',peopleIds:['p-dad'],placeIds:['pl-phoenix'],tagIds:['t-family'],mediaIds:[],relatedEntryIds:[]},
  {id:'m-pokemon',title:"Playing Pokémon at Grandma's",body:"I remember sitting on the floor at Grandma's house, trading turns and trying not to lose the save file.",entryType:'memory',eventDate:{precision:'age',age:8,confidence:'guess'},recordTime:'2026-09-20T10:00:00Z',createdAt:'2026-09-20T10:00:00Z',updatedAt:'2026-09-20T10:00:00Z',importance:2,status:'active',peopleIds:['p-grandma'],placeIds:['pl-grandma'],tagIds:['t-childhood'],mediaIds:[],relatedEntryIds:[]},
  {id:'m-unknown',title:'A song from the back seat',body:'No date yet—just the feeling of a long drive and everyone singing the chorus too loudly.',entryType:'story',eventDate:{precision:'unknown',confidence:'unknown'},recordTime:'2026-09-20T10:00:00Z',createdAt:'2026-09-20T10:00:00Z',updatedAt:'2026-09-20T10:00:00Z',importance:1,status:'active',peopleIds:[],placeIds:[],tagIds:['t-family'],mediaIds:[],relatedEntryIds:[]}
 ] }
